### ISSUE TITLE
Only 3 Presets are visible in HomeKit

### ISSUE THREAD

**Issue by jerielsr** [goodshort/homebridge-wled-preset#1]
I only have 3 presets available to select from in the HomeKit app although I have entered 6 in the HomeBridge Config. I've tried this multiple times even with a different ESP board for WLED but no luck. I only ever get to chose the first 3 presets.

**Plugin Config:**

```json
        {
            "name": "Jeriel's LED Strip",
            "ip": "10.0.4.176",
            "presetNames": [
                {
                    "presetNb": 1,
                    "name": "Fireworks"
                },
                {
                    "presetNb": 2,
                    "name": "Peachy"
                },
                {
                    "presetNb": 3,
                    "name": "Ice Fire"
                },
                {
                    "presetNb": 4,
                    "name": "Fire"
                },
                {
                    "presetNb": 5,
                    "name": "Aurora"
                }
            ],
            "platform": "WledPreset"
        }
```

**Screenshots:**
![IMG_4D417F9ED714-1](https://user-images.githubusercontent.com/40922106/143262422-fdc490bf-89b4-4d56-bcae-ebfd40fde979.jpeg)

**Environment:**

* **Plugin Version**: v0.1.1
* **Homebridge Version**: v1.3.8
* **Node.js Version**: v14.18.0
* **NPM Version**: v6.14.15
* **Operating System**: Docker

**Comment by agoodshort** [comment]
Hi Jeriel,

This repo has been on standby for quite some times as I moved my leds in some other place in the house before completing this.
At the moment, only 3 presets can be added because it is "hard-coded" (see [these lines](https://github.com/goodshort/homebridge-wled-preset/blob/master/src/platformAccessory.ts#L125-L150)).

I should be able to start working again on the project during December. I will keep this issue open as a reminder, but that was defnitely something I wanted to implement. I will comment back here when I will have implemented changes.

Adrien

**Comment by agoodshort** [comment]
Hi Jeriel,
I just pushed version 0.2.0, when configuring the plugin you will be now asked how many presets are configured on your WLED interface. The number you indicate assumes that your presets ID in WLED are incrementing 1 by 1 starting from 1 (eg. if you have 2 presets with ID 2 and 40, you will need to enter 40).
Hope that make sense.

Please note: At the moment the plugin only allows to use 1 WLED/ESP board.

Feel free to reach out if you have any feedback/requests.

Adrien

**Comment by jerielsr** [comment]
Hey Adrien, 

Thanks for the update! The numbering makes sense to me.

I just gave it a try, I have 9 presets set up, so I configured that appropriately on the plugin settings. However I still only see the roller dial for the first 3 presets. The first three presets within the roller dial in HomeKit do work in accordance with the WLED Preset numbers. Differently to before, I now see these other 5 tiles for each preset beyond preset 3, however I cannot interact with them (as in turn them on or off)

My config is now as follows:

**Plugin Config:**
```
        {
            "name": "LED Strip",
            "ip": "10.0.4.176",
            "presetsNb": 9,
            "platform": "WledPreset"
        }
```

I've also tried adding the preset names to the config as below, but no difference.

```
        {
            "name": "LED Strip",
            "ip": "10.0.4.176",
            "presetsNb": 9,
            "presetNames": [
                            {
                                "presetNb": 1,
                                "name": "Fireworks"
                            },
                            {
                                "presetNb": 2,
                                "name": "Peachy"
                            },
                            {
                                "presetNb": 3,
                                "name": "Ice Fire"
                            },
                            {
                                "presetNb": 4,
                                "name": "Fire"
                            },
                            {
                                "presetNb": 5,
                                "name": "Aurora"
                            }
                        ],
            "platform": "WledPreset"
        }
```

**Screenshots:**
![IMG_1897](https://user-images.githubusercontent.com/40922106/144578938-44aba526-1976-4db7-a728-66537d395bcd.PNG)

**Comment by agoodshort** [comment]
Hi,

The first config is the way to go now, I removed the presetNames for now (planning to implement it back in the future, it is just a bit more complicated to implement now as I use a loop).

To fix the tiles, I'd recommend to go to your Homebridge UI and use the "Remove Single Cached Accessory" feature. I faced the same behavior as well. I think I am doing something wrong somewhere with the cached accessories. I will try to figure this out in the future.

Edit:
As I am still fairly new to this and the project is not quite stable yet, I might recommend you to run the plugin as a [Child bridge](https://github.com/homebridge/homebridge/wiki/Child-Bridges). The way I am working on it at the moment is through a separate homebridge instance running on my development machine, and quite often unpair and pair again.

**Comment by osxster** [comment]
Hello,

Any way you can fix this issue (I assume it has something to do with these changes to allow for more presets) to allow for more than 1 WLED instance?  If I add a second WLED instance, HomeBridge keeps crashing and goes into a restart loop.  If I need to open a new 'issue' I can.

**Comment by agoodshort** [comment]
@osxster Yes we can definitely open another issue for this one. I will try to get this one solved ASAP as it annoys me as well.

**Comment by osxster** [comment]
Sounds great!  Just started deploying WLED and wanted to figure out a way to get these into my HomeKit environment.  So I'm obviously new to your plugin.  I also was trying to play with Playlists, was hoping that a playlist would show up in WLED Preset as a preset, since it is in the same menu in WLED.  However if I create a playlist, and execute the playlist from WLED, the presets no longer work in WLED Preset.  The power button works, but the playlist keeps playing.  I have to go into WLED and manually select a Preset for WLED Preset to start allowing you to select a preset again.

**Comment by agoodshort** [comment]
Closing this issue as [v0.3.0](https://github.com/goodshort/homebridge-wled-preset/releases/tag/v0.3.0) allows to add as many presets as desired.
