### ISSUE TITLE
Home Kit Bulb State is based off of Brightness toggle

### ISSUE THREAD

**Issue by osxster** [goodshort/homebridge-wled-preset#2]
Hello,

I've added this to my HomeBridge installation and it works.  However the issue I see is that the Bulb Status in HomeKit seems to be linked to the brightness toggle rather than if the LED's controlled by WLED are actually on or off.  So if I go into HomeKit, hit the power button, the LED's attached to my WLED controller turn off.  However the Bulb in HomeKit still says the 'lights' are on.  Then looking in the 'Room' in HomeKit, it shows that light is on when it is actually off.  If I move the brightness toggle all the way down, the bulb in HomeKit shows it off and the LED lights are off too, but it would be nice if hitting the power button to turn off the LED's also showed the Light off in HomeKit.

**Comment by agoodshort** [comment]
@osxster I have done a good clean up on the plugin and now removed the Lightbulb brightness slider. My thinking was that presets on the WLED interface are anyway set with a brightness value.
I might add back a brightness slider later on if this is a request/need.

Regarding the state of the LED strip shown in HomeKit, it is now updating properly. Please note that the update is not instant as a change on the WLED interface does not push any message to the plugin. Re-opening the Home app or waiting 1-2 minutes will update the status of the LED strip.

Feel free to re-open/comment/open a new issue. I am happy to gather feedback.

**Comment by osxster** [comment]
Hello, thanks this works now.  I did have to disable the plugin and enable it again for HomeKit to pick up the changes.  Nothing I did (restarting HomeBridge, closing, opening HomeApp, etc.) would let me see the changes.  However I kind of like the idea of a brightness toggle.  My first deployment of WLED was for Garage Lights for ceiling lights.  I will also deploy this in other places.  But it is nice to be able to say "Hey Siri, set the garage lights to 50%" for example.  Same with putting this in a living room or anywhere else.  Something to think about.

**Comment by agoodshort** [comment]
I agree, brightness would be great if it works properly. I just need to figure out a few other things first. It is the first time I write a plugin, so it takes a bit of practice.
I might have an idea why the plugin struggles so much to deal with updates/changes. Might be related with the way I generate UUID for the devices. I'll have a look at that.
