### ISSUE TITLE
Plugin struggle to load new features after update

### ISSUE THREAD

**Issue by agoodshort** [goodshort/homebridge-wled-preset#6]
After a restart or update the plugin seem to struggle to load the new feature/changes applied on the devices/plugin.
This might be related with the way the UUID is being generated, as at the moment it is based on the IP address of the device. To investigate...

**Comment by osxster** [comment]
The work-around I had for this after updating wled-preset was to disable the plugin, allow the devices to disappear from HomeKit, and then reenable, allow them to come back, and then the new features showed up.  Just wanted to post this here if it helps in your troubleshooting, anyone else having this issue and looking for a quick work-around until it can be fixed, or another solution comes up.  Restarting HomeBridge had no effect for me without performing the above steps.

Good work in this so far!

**Comment by agoodshort** [comment]
The v0.5.0 should have resolve this. Feel free to comment here if you think it is not the case.
